[font]
size = 25

[font.normal]
#family = "UbuntuMono Nerd Font"
family = "JetBrains Mono"

[window]
#decorations = "none"

[window.dimensions]
columns = 100
lines = 50

[window.padding]
x = 7
y = 0

[general]

# themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[terminal]

[terminal.shell]
program = "tmux"
