#!/bin/bash

BACKUPS_DESTINATION="/Volumes/OurStuff/Ivan/backups/weekly"
# format:
# rsync -a --delete --quiet /path/to/backup /location/of/backup

# stop the script if an error occurs
set -e

# For Mac Device
rsync -a --delete --quiet --exclude="{"/Users/ivan/.cache/*"}" /Users/ivan $BACKUPS_DESTINATION/home

# For Linux device.
#rsync -a --delete --quiet --exclude="{"/home/ivan/.cache/*"}" /home/ivan $BACKUPS_DESTINATION/home
#rsync -a --delete --quiet /etc $BACKUPS_DESTINATION

echo "Made weekly backups on: $(date)" >> /var/log/backup.log